// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDIYWkoYClC6RlP2q7GP4OY1c2eH_ofy8',
    appId: '1:391377882165:web:1cc1f24195a7516d04b57c',
    messagingSenderId: '391377882165',
    projectId: 'assignment3-24947',
    authDomain: 'assignment3-24947.firebaseapp.com',
    storageBucket: 'assignment3-24947.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM6nzVclLqta3AD65OQvj09E4ERsWZ4-E',
    appId: '1:391377882165:android:c0490090286e6ce904b57c',
    messagingSenderId: '391377882165',
    projectId: 'assignment3-24947',
    storageBucket: 'assignment3-24947.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDIYWkoYClC6RlP2q7GP4OY1c2eH_ofy8',
    appId: '1:391377882165:web:52b852febd915f2c04b57c',
    messagingSenderId: '391377882165',
    projectId: 'assignment3-24947',
    authDomain: 'assignment3-24947.firebaseapp.com',
    storageBucket: 'assignment3-24947.appspot.com',
  );
}
